root = "."
tmp_dir = "tmp"

[build]
  bin = "./any-sync-bundle"
  cmd = "go build -o ./any-sync-bundle"
  delay = 500
  exclude_dir = ["assets", "tmp", "vendor"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "./any-sync-bundle start"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "yaml", "env"]
  kill_delay = "1s"
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true