# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# https://github.com/goreleaser/goreleaser/pull/4391
version: 2

report_sizes: true

builds:
  # https://goreleaser.com/customization/builds/go/
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -w -s
      - -X github.com/grishy/any-sync-bundle/cmd.version={{.Version}}
      - -X github.com/grishy/any-sync-bundle/cmd.commit={{.Commit}}
      - -X github.com/grishy/any-sync-bundle/cmd.date={{.CommitDate}}
    targets:
      # First class ports: https://go.dev/wiki/PortingPolicy#first-class-ports
      - go_118_first_class
      - freebsd_arm64
      - freebsd_amd64
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  # https://goreleaser.com/customization/archive/
  - formats: ["tar.gz"]

checksum:
  # https://goreleaser.com/customization/checksum/
  name_template: "checksums.txt"

release:
  # https://goreleaser.com/customization/release/
  target_commitish: "{{ .Commit }}"
  mode: replace
  header: |
    ## ⚠️ For information on how to install and use, please see [README.md](https://github.com/grishy/any-sync-bundle#readme)
  footer: |
    Your PRs and issues are welcome! Thanks 🙂
  disable: false
  skip_upload: false

changelog:
  # https://goreleaser.com/customization/changelog/
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
  groups:
    - title: "New Features"
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
