# Any-Sync-Bundle (AIO) with S3 Storage (MinIO)
#
# Usage:
#   docker compose -f compose.s3.yml up -d
#
# This runs the all-in-one bundle (embedded MongoDB/Redis) with MinIO for S3 storage.
# MinIO Console: http://localhost:9001 (minioadmin/minioadmin)

services:
  minio:
    image: docker.io/minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: any-sync-bundle-minio
    command: ["server", "/data", "--console-address", ":9001", "--address", ":9000"]
    restart: unless-stopped
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio:/data
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3

  # One-shot container to create buckets on startup
  minio-init:
    image: docker.io/minio/mc:RELEASE.2025-08-13T08-35-41Z
    container_name: any-sync-bundle-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      until mc alias set minio http://minio:9000 minioadmin minioadmin; do
        echo 'Waiting for MinIO...'; sleep 1;
      done;
      mc mb minio/anytype-data --ignore-existing;
      echo 'Bucket anytype-data created';
      exit 0;
      "

  any-sync-bundle:
    image: ghcr.io/grishy/any-sync-bundle:1.3.1-2026-02-16
    container_name: any-sync-bundle-aio
    restart: unless-stopped
    depends_on:
      minio:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
    ports:
      - "33010:33010"
      - "33020:33020/udp"
    volumes:
      - ./data:/data
    environment:
      # Advertise addresses clients should use. Replace with server's hostname/IP.
      ANY_SYNC_BUNDLE_INIT_EXTERNAL_ADDRS: "192.168.100.9"
      # S3 Storage (MinIO)
      ANY_SYNC_BUNDLE_INIT_S3_BUCKET: "anytype-data"
      ANY_SYNC_BUNDLE_INIT_S3_ENDPOINT: "http://minio:9000"
      ANY_SYNC_BUNDLE_INIT_S3_FORCE_PATH_STYLE: "true"
      # ANY_SYNC_BUNDLE_INIT_S3_REGION: "us-east-1"  # Only if MinIO uses custom region
      # S3 Credentials (via standard AWS env vars)
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      # Storage limit per space in bytes (default: 1 TiB)
      # Examples:   1 GiB = 1073741824
      #            10 GiB = 10737418240
      #           150 GiB = 161061273600
      #             1 TiB = 1099511627776 (default)
      #             2 TiB = 2199023255552
      # ANY_SYNC_BUNDLE_INIT_FILENODE_DEFAULT_LIMIT: "1099511627776"
