services:
  mongo:
    image: docker.io/mongo:7.0.16
    command:
      - "--replSet"
      - "rs0"
      - "--port"
      - "27017"
    ports:
      - 27017:27017
    healthcheck:
      test: test $$(mongosh --port 27017 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:27017\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s
    volumes:
      - "./data/mongo:/data/db:Z"

  redis:
    image: docker.io/redis/redis-stack-server:7.4.0-v2
    command:
      - "redis-server"
      - "--port"
      - "6379"
      - "--dir"
      - "/data/"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "noeviction"
      - "--protected-mode"
      - "no"
      - "--loadmodule"
      - "/opt/redis-stack/lib/redisbloom.so"
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "-p", "6379", "incr", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3
    volumes:
      - ./data/redis:/data
