# Example: Any-Sync-Bundle with embedded MongoDB and Redis (all-in-one image)
#
# Usage:
#   docker compose -f compose.aio.yml up -d
#
# The bundle image already contains MongoDB and Redis. Only the bundle service is required.

services:
  any-sync-bundle:
    image: ghcr.io/grishy/any-sync-bundle:1.3.1-2026-02-16
    container_name: any-sync-bundle-aio
    restart: unless-stopped
    ports:
      - "33010:33010"
      - "33020:33020/udp"
    volumes:
      - ./data:/data
    environment:
      # Advertise addresses clients should use. Replace with your server hostname/IP.
      ANY_SYNC_BUNDLE_INIT_EXTERNAL_ADDRS: "192.168.100.9"
      # Storage limit per space in bytes (default: 1 TiB)
      # Examples:   1 GiB = 1073741824
      #            10 GiB = 10737418240
      #           150 GiB = 161061273600
      #             1 TiB = 1099511627776 (default)
      #             2 TiB = 2199023255552
      # ANY_SYNC_BUNDLE_INIT_FILENODE_DEFAULT_LIMIT: "1099511627776"
