# For local development or reference only

services:
  mongo:
    image: docker.io/mongo:8.0.4
    command:
      - "--replSet"
      - "rs0"
      - "--port"
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data

  redis:
    image: docker.io/redis/redis-stack-server:7.4.0-v2
    command:
      - "redis-server"
      - "--port"
      - "6379"
      - "--dir"
      - "/data/"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "256mb"
      - "--maxmemory-policy"
      - "noeviction"
      - "--protected-mode"
      - "no"
      - "--loadmodule"
      - "/opt/redis-stack/lib/redisbloom.so"
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
