// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: index.proto

package indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CidEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,1,opt,name=size"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Refs        int32                  `protobuf:"varint,4,opt,name=refs"`
	xxx_hidden_Version     uint32                 `protobuf:"varint,5,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CidEntry) Reset() {
	*x = CidEntry{}
	mi := &file_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidEntry) ProtoMessage() {}

func (x *CidEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CidEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *CidEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *CidEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *CidEntry) GetRefs() int32 {
	if x != nil {
		return x.xxx_hidden_Refs
	}
	return 0
}

func (x *CidEntry) GetVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *CidEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CidEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CidEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CidEntry) SetRefs(v int32) {
	x.xxx_hidden_Refs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CidEntry) SetVersion(v uint32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CidEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CidEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CidEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CidEntry) HasRefs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CidEntry) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CidEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Size = 0
}

func (x *CidEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *CidEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *CidEntry) ClearRefs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Refs = 0
}

func (x *CidEntry) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

type CidEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Size       *uint64
	CreateTime *int64
	UpdateTime *int64
	Refs       *int32
	Version    *uint32
}

func (b0 CidEntry_builder) Build() *CidEntry {
	m0 := &CidEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Refs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Refs = *b.Refs
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type GroupEntry struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GroupId      *string                `protobuf:"bytes,1,opt,name=groupId"`
	xxx_hidden_CreateTime   int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime   int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Size         uint64                 `protobuf:"varint,4,opt,name=size"`
	xxx_hidden_CidCount     uint64                 `protobuf:"varint,5,opt,name=cidCount"`
	xxx_hidden_Limit        uint64                 `protobuf:"varint,6,opt,name=limit"`
	xxx_hidden_AccountLimit uint64                 `protobuf:"varint,7,opt,name=accountLimit"`
	xxx_hidden_SpaceIds     []string               `protobuf:"bytes,8,rep,name=spaceIds"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GroupEntry) Reset() {
	*x = GroupEntry{}
	mi := &file_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEntry) ProtoMessage() {}

func (x *GroupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupEntry) GetGroupId() string {
	if x != nil {
		if x.xxx_hidden_GroupId != nil {
			return *x.xxx_hidden_GroupId
		}
		return ""
	}
	return ""
}

func (x *GroupEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *GroupEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *GroupEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *GroupEntry) GetCidCount() uint64 {
	if x != nil {
		return x.xxx_hidden_CidCount
	}
	return 0
}

func (x *GroupEntry) GetLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GroupEntry) GetAccountLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_AccountLimit
	}
	return 0
}

func (x *GroupEntry) GetSpaceIds() []string {
	if x != nil {
		return x.xxx_hidden_SpaceIds
	}
	return nil
}

func (x *GroupEntry) SetGroupId(v string) {
	x.xxx_hidden_GroupId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *GroupEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *GroupEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *GroupEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *GroupEntry) SetCidCount(v uint64) {
	x.xxx_hidden_CidCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *GroupEntry) SetLimit(v uint64) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *GroupEntry) SetAccountLimit(v uint64) {
	x.xxx_hidden_AccountLimit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *GroupEntry) SetSpaceIds(v []string) {
	x.xxx_hidden_SpaceIds = v
}

func (x *GroupEntry) HasGroupId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GroupEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GroupEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GroupEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GroupEntry) HasCidCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GroupEntry) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GroupEntry) HasAccountLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *GroupEntry) ClearGroupId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GroupId = nil
}

func (x *GroupEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *GroupEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *GroupEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

func (x *GroupEntry) ClearCidCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CidCount = 0
}

func (x *GroupEntry) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Limit = 0
}

func (x *GroupEntry) ClearAccountLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_AccountLimit = 0
}

type GroupEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GroupId      *string
	CreateTime   *int64
	UpdateTime   *int64
	Size         *uint64
	CidCount     *uint64
	Limit        *uint64
	AccountLimit *uint64
	SpaceIds     []string
}

func (b0 GroupEntry_builder) Build() *GroupEntry {
	m0 := &GroupEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GroupId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_GroupId = b.GroupId
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CidCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_CidCount = *b.CidCount
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.AccountLimit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_AccountLimit = *b.AccountLimit
	}
	x.xxx_hidden_SpaceIds = b.SpaceIds
	return m0
}

type SpaceEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GroupId     *string                `protobuf:"bytes,1,opt,name=groupId"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,4,opt,name=size"`
	xxx_hidden_FileCount   uint32                 `protobuf:"varint,5,opt,name=fileCount"`
	xxx_hidden_CidCount    uint64                 `protobuf:"varint,6,opt,name=cidCount"`
	xxx_hidden_Limit       uint64                 `protobuf:"varint,7,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SpaceEntry) Reset() {
	*x = SpaceEntry{}
	mi := &file_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEntry) ProtoMessage() {}

func (x *SpaceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpaceEntry) GetGroupId() string {
	if x != nil {
		if x.xxx_hidden_GroupId != nil {
			return *x.xxx_hidden_GroupId
		}
		return ""
	}
	return ""
}

func (x *SpaceEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *SpaceEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *SpaceEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *SpaceEntry) GetFileCount() uint32 {
	if x != nil {
		return x.xxx_hidden_FileCount
	}
	return 0
}

func (x *SpaceEntry) GetCidCount() uint64 {
	if x != nil {
		return x.xxx_hidden_CidCount
	}
	return 0
}

func (x *SpaceEntry) GetLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SpaceEntry) SetGroupId(v string) {
	x.xxx_hidden_GroupId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *SpaceEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *SpaceEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *SpaceEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *SpaceEntry) SetFileCount(v uint32) {
	x.xxx_hidden_FileCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *SpaceEntry) SetCidCount(v uint64) {
	x.xxx_hidden_CidCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *SpaceEntry) SetLimit(v uint64) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *SpaceEntry) HasGroupId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SpaceEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SpaceEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SpaceEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SpaceEntry) HasFileCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SpaceEntry) HasCidCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SpaceEntry) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *SpaceEntry) ClearGroupId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GroupId = nil
}

func (x *SpaceEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *SpaceEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *SpaceEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

func (x *SpaceEntry) ClearFileCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_FileCount = 0
}

func (x *SpaceEntry) ClearCidCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CidCount = 0
}

func (x *SpaceEntry) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Limit = 0
}

type SpaceEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GroupId    *string
	CreateTime *int64
	UpdateTime *int64
	Size       *uint64
	FileCount  *uint32
	CidCount   *uint64
	Limit      *uint64
}

func (b0 SpaceEntry_builder) Build() *SpaceEntry {
	m0 := &SpaceEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GroupId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_GroupId = b.GroupId
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Size = *b.Size
	}
	if b.FileCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_FileCount = *b.FileCount
	}
	if b.CidCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_CidCount = *b.CidCount
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type FileEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cids        []string               `protobuf:"bytes,1,rep,name=cids"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,3,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,4,opt,name=updateTime"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileEntry) GetCids() []string {
	if x != nil {
		return x.xxx_hidden_Cids
	}
	return nil
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *FileEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *FileEntry) SetCids(v []string) {
	x.xxx_hidden_Cids = v
}

func (x *FileEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *FileEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *FileEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *FileEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FileEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FileEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *FileEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreateTime = 0
}

func (x *FileEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UpdateTime = 0
}

type FileEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cids       []string
	Size       *uint64
	CreateTime *int64
	UpdateTime *int64
}

func (b0 FileEntry_builder) Build() *FileEntry {
	m0 := &FileEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cids = b.Cids
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	return m0
}

type Store struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cids        *[]*CidEntry           `protobuf:"bytes,1,rep,name=cids"`
	xxx_hidden_Groups      *[]*GroupEntry         `protobuf:"bytes,2,rep,name=groups"`
	xxx_hidden_Spaces      *[]*SpaceEntry         `protobuf:"bytes,3,rep,name=spaces"`
	xxx_hidden_Files       *[]*FileEntry          `protobuf:"bytes,4,rep,name=files"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,10,opt,name=createTime"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Store) GetCids() []*CidEntry {
	if x != nil {
		if x.xxx_hidden_Cids != nil {
			return *x.xxx_hidden_Cids
		}
	}
	return nil
}

func (x *Store) GetGroups() []*GroupEntry {
	if x != nil {
		if x.xxx_hidden_Groups != nil {
			return *x.xxx_hidden_Groups
		}
	}
	return nil
}

func (x *Store) GetSpaces() []*SpaceEntry {
	if x != nil {
		if x.xxx_hidden_Spaces != nil {
			return *x.xxx_hidden_Spaces
		}
	}
	return nil
}

func (x *Store) GetFiles() []*FileEntry {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *Store) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *Store) SetCids(v []*CidEntry) {
	x.xxx_hidden_Cids = &v
}

func (x *Store) SetGroups(v []*GroupEntry) {
	x.xxx_hidden_Groups = &v
}

func (x *Store) SetSpaces(v []*SpaceEntry) {
	x.xxx_hidden_Spaces = &v
}

func (x *Store) SetFiles(v []*FileEntry) {
	x.xxx_hidden_Files = &v
}

func (x *Store) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Store) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Store) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CreateTime = 0
}

type Store_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cids       []*CidEntry
	Groups     []*GroupEntry
	Spaces     []*SpaceEntry
	Files      []*FileEntry
	CreateTime *int64
}

func (b0 Store_builder) Build() *Store {
	m0 := &Store{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cids = &b.Cids
	x.xxx_hidden_Groups = &b.Groups
	x.xxx_hidden_Spaces = &b.Spaces
	x.xxx_hidden_Files = &b.Files
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	return m0
}

var File_index_proto protoreflect.FileDescriptor

var file_index_proto_rawDesc = string([]byte{
	0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x43, 0x69, 0x64, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x66, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x72, 0x65, 0x66, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xec, 0x01, 0x0a, 0x0a, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x69, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x69, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x0a, 0x53, 0x70, 0x61, 0x63, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a,
	0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x69, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x63, 0x69, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x73, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd2, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x12, 0x25, 0x0a, 0x04, 0x63, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x64, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x04, 0x63, 0x69, 0x64, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70,
	0x62, 0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x67, 0x72,
	0x6f, 0x75, 0x70, 0x73, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x2e, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x73, 0x12, 0x28, 0x0a, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x0f, 0x5a, 0x0d, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x70, 0x62, 0x62, 0x08, 0x65, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x70, 0xe8, 0x07,
})

var file_index_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_index_proto_goTypes = []any{
	(*CidEntry)(nil),   // 0: indexpb.CidEntry
	(*GroupEntry)(nil), // 1: indexpb.GroupEntry
	(*SpaceEntry)(nil), // 2: indexpb.SpaceEntry
	(*FileEntry)(nil),  // 3: indexpb.FileEntry
	(*Store)(nil),      // 4: indexpb.Store
}
var file_index_proto_depIdxs = []int32{
	0, // 0: indexpb.Store.cids:type_name -> indexpb.CidEntry
	1, // 1: indexpb.Store.groups:type_name -> indexpb.GroupEntry
	2, // 2: indexpb.Store.spaces:type_name -> indexpb.SpaceEntry
	3, // 3: indexpb.Store.files:type_name -> indexpb.FileEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_index_proto_init() }
func file_index_proto_init() {
	if File_index_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_index_proto_rawDesc), len(file_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_index_proto_goTypes,
		DependencyIndexes: file_index_proto_depIdxs,
		MessageInfos:      file_index_proto_msgTypes,
	}.Build()
	File_index_proto = out.File
	file_index_proto_goTypes = nil
	file_index_proto_depIdxs = nil
}
