// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.1
// source: store.proto

package indexpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CidEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,1,opt,name=size"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Refs        int32                  `protobuf:"varint,4,opt,name=refs"`
	xxx_hidden_Version     uint32                 `protobuf:"varint,5,opt,name=version"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CidEntry) Reset() {
	*x = CidEntry{}
	mi := &file_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CidEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CidEntry) ProtoMessage() {}

func (x *CidEntry) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CidEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *CidEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *CidEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *CidEntry) GetRefs() int32 {
	if x != nil {
		return x.xxx_hidden_Refs
	}
	return 0
}

func (x *CidEntry) GetVersion() uint32 {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return 0
}

func (x *CidEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *CidEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *CidEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *CidEntry) SetRefs(v int32) {
	x.xxx_hidden_Refs = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *CidEntry) SetVersion(v uint32) {
	x.xxx_hidden_Version = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *CidEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CidEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *CidEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CidEntry) HasRefs() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *CidEntry) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *CidEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Size = 0
}

func (x *CidEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *CidEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *CidEntry) ClearRefs() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Refs = 0
}

func (x *CidEntry) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Version = 0
}

type CidEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Size       *uint64
	CreateTime *int64
	UpdateTime *int64
	Refs       *int32
	Version    *uint32
}

func (b0 CidEntry_builder) Build() *CidEntry {
	m0 := &CidEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Refs != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Refs = *b.Refs
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Version = *b.Version
	}
	return m0
}

type GroupEntry struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GroupId      *string                `protobuf:"bytes,1,opt,name=groupId"`
	xxx_hidden_CreateTime   int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime   int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Size         uint64                 `protobuf:"varint,4,opt,name=size"`
	xxx_hidden_CidCount     uint64                 `protobuf:"varint,5,opt,name=cidCount"`
	xxx_hidden_Limit        uint64                 `protobuf:"varint,6,opt,name=limit"`
	xxx_hidden_AccountLimit uint64                 `protobuf:"varint,7,opt,name=accountLimit"`
	xxx_hidden_SpaceIds     []string               `protobuf:"bytes,8,rep,name=spaceIds"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GroupEntry) Reset() {
	*x = GroupEntry{}
	mi := &file_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEntry) ProtoMessage() {}

func (x *GroupEntry) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GroupEntry) GetGroupId() string {
	if x != nil {
		if x.xxx_hidden_GroupId != nil {
			return *x.xxx_hidden_GroupId
		}
		return ""
	}
	return ""
}

func (x *GroupEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *GroupEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *GroupEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *GroupEntry) GetCidCount() uint64 {
	if x != nil {
		return x.xxx_hidden_CidCount
	}
	return 0
}

func (x *GroupEntry) GetLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *GroupEntry) GetAccountLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_AccountLimit
	}
	return 0
}

func (x *GroupEntry) GetSpaceIds() []string {
	if x != nil {
		return x.xxx_hidden_SpaceIds
	}
	return nil
}

func (x *GroupEntry) SetGroupId(v string) {
	x.xxx_hidden_GroupId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *GroupEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *GroupEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *GroupEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *GroupEntry) SetCidCount(v uint64) {
	x.xxx_hidden_CidCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *GroupEntry) SetLimit(v uint64) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *GroupEntry) SetAccountLimit(v uint64) {
	x.xxx_hidden_AccountLimit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *GroupEntry) SetSpaceIds(v []string) {
	x.xxx_hidden_SpaceIds = v
}

func (x *GroupEntry) HasGroupId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GroupEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GroupEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GroupEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GroupEntry) HasCidCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *GroupEntry) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *GroupEntry) HasAccountLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *GroupEntry) ClearGroupId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GroupId = nil
}

func (x *GroupEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *GroupEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *GroupEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

func (x *GroupEntry) ClearCidCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CidCount = 0
}

func (x *GroupEntry) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Limit = 0
}

func (x *GroupEntry) ClearAccountLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_AccountLimit = 0
}

type GroupEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GroupId      *string
	CreateTime   *int64
	UpdateTime   *int64
	Size         *uint64
	CidCount     *uint64
	Limit        *uint64
	AccountLimit *uint64
	SpaceIds     []string
}

func (b0 GroupEntry_builder) Build() *GroupEntry {
	m0 := &GroupEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GroupId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_GroupId = b.GroupId
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CidCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_CidCount = *b.CidCount
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_Limit = *b.Limit
	}
	if b.AccountLimit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_AccountLimit = *b.AccountLimit
	}
	x.xxx_hidden_SpaceIds = b.SpaceIds
	return m0
}

type SpaceEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_GroupId     *string                `protobuf:"bytes,1,opt,name=groupId"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,2,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,3,opt,name=updateTime"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,4,opt,name=size"`
	xxx_hidden_FileCount   uint32                 `protobuf:"varint,5,opt,name=fileCount"`
	xxx_hidden_CidCount    uint64                 `protobuf:"varint,6,opt,name=cidCount"`
	xxx_hidden_Limit       uint64                 `protobuf:"varint,7,opt,name=limit"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SpaceEntry) Reset() {
	*x = SpaceEntry{}
	mi := &file_store_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpaceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceEntry) ProtoMessage() {}

func (x *SpaceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SpaceEntry) GetGroupId() string {
	if x != nil {
		if x.xxx_hidden_GroupId != nil {
			return *x.xxx_hidden_GroupId
		}
		return ""
	}
	return ""
}

func (x *SpaceEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *SpaceEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *SpaceEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *SpaceEntry) GetFileCount() uint32 {
	if x != nil {
		return x.xxx_hidden_FileCount
	}
	return 0
}

func (x *SpaceEntry) GetCidCount() uint64 {
	if x != nil {
		return x.xxx_hidden_CidCount
	}
	return 0
}

func (x *SpaceEntry) GetLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *SpaceEntry) SetGroupId(v string) {
	x.xxx_hidden_GroupId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *SpaceEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *SpaceEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *SpaceEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *SpaceEntry) SetFileCount(v uint32) {
	x.xxx_hidden_FileCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *SpaceEntry) SetCidCount(v uint64) {
	x.xxx_hidden_CidCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *SpaceEntry) SetLimit(v uint64) {
	x.xxx_hidden_Limit = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 7)
}

func (x *SpaceEntry) HasGroupId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SpaceEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *SpaceEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SpaceEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *SpaceEntry) HasFileCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *SpaceEntry) HasCidCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *SpaceEntry) HasLimit() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *SpaceEntry) ClearGroupId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_GroupId = nil
}

func (x *SpaceEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_CreateTime = 0
}

func (x *SpaceEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_UpdateTime = 0
}

func (x *SpaceEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Size = 0
}

func (x *SpaceEntry) ClearFileCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_FileCount = 0
}

func (x *SpaceEntry) ClearCidCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_CidCount = 0
}

func (x *SpaceEntry) ClearLimit() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_Limit = 0
}

type SpaceEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	GroupId    *string
	CreateTime *int64
	UpdateTime *int64
	Size       *uint64
	FileCount  *uint32
	CidCount   *uint64
	Limit      *uint64
}

func (b0 SpaceEntry_builder) Build() *SpaceEntry {
	m0 := &SpaceEntry{}
	b, x := &b0, m0
	_, _ = b, x
	if b.GroupId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_GroupId = b.GroupId
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Size = *b.Size
	}
	if b.FileCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_FileCount = *b.FileCount
	}
	if b.CidCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_CidCount = *b.CidCount
	}
	if b.Limit != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 7)
		x.xxx_hidden_Limit = *b.Limit
	}
	return m0
}

type FileEntry struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cids        []string               `protobuf:"bytes,1,rep,name=cids"`
	xxx_hidden_Size        uint64                 `protobuf:"varint,2,opt,name=size"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,3,opt,name=createTime"`
	xxx_hidden_UpdateTime  int64                  `protobuf:"varint,4,opt,name=updateTime"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_store_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FileEntry) GetCids() []string {
	if x != nil {
		return x.xxx_hidden_Cids
	}
	return nil
}

func (x *FileEntry) GetSize() uint64 {
	if x != nil {
		return x.xxx_hidden_Size
	}
	return 0
}

func (x *FileEntry) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *FileEntry) GetUpdateTime() int64 {
	if x != nil {
		return x.xxx_hidden_UpdateTime
	}
	return 0
}

func (x *FileEntry) SetCids(v []string) {
	x.xxx_hidden_Cids = v
}

func (x *FileEntry) SetSize(v uint64) {
	x.xxx_hidden_Size = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *FileEntry) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *FileEntry) SetUpdateTime(v int64) {
	x.xxx_hidden_UpdateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *FileEntry) HasSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *FileEntry) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *FileEntry) HasUpdateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *FileEntry) ClearSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Size = 0
}

func (x *FileEntry) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CreateTime = 0
}

func (x *FileEntry) ClearUpdateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_UpdateTime = 0
}

type FileEntry_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cids       []string
	Size       *uint64
	CreateTime *int64
	UpdateTime *int64
}

func (b0 FileEntry_builder) Build() *FileEntry {
	m0 := &FileEntry{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cids = b.Cids
	if b.Size != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Size = *b.Size
	}
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	if b.UpdateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_UpdateTime = *b.UpdateTime
	}
	return m0
}

type Store struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cids        *[]*CidEntry           `protobuf:"bytes,1,rep,name=cids"`
	xxx_hidden_Groups      *[]*GroupEntry         `protobuf:"bytes,2,rep,name=groups"`
	xxx_hidden_Spaces      *[]*SpaceEntry         `protobuf:"bytes,3,rep,name=spaces"`
	xxx_hidden_Files       *[]*FileEntry          `protobuf:"bytes,4,rep,name=files"`
	xxx_hidden_CreateTime  int64                  `protobuf:"varint,10,opt,name=createTime"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_store_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_store_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Store) GetCids() []*CidEntry {
	if x != nil {
		if x.xxx_hidden_Cids != nil {
			return *x.xxx_hidden_Cids
		}
	}
	return nil
}

func (x *Store) GetGroups() []*GroupEntry {
	if x != nil {
		if x.xxx_hidden_Groups != nil {
			return *x.xxx_hidden_Groups
		}
	}
	return nil
}

func (x *Store) GetSpaces() []*SpaceEntry {
	if x != nil {
		if x.xxx_hidden_Spaces != nil {
			return *x.xxx_hidden_Spaces
		}
	}
	return nil
}

func (x *Store) GetFiles() []*FileEntry {
	if x != nil {
		if x.xxx_hidden_Files != nil {
			return *x.xxx_hidden_Files
		}
	}
	return nil
}

func (x *Store) GetCreateTime() int64 {
	if x != nil {
		return x.xxx_hidden_CreateTime
	}
	return 0
}

func (x *Store) SetCids(v []*CidEntry) {
	x.xxx_hidden_Cids = &v
}

func (x *Store) SetGroups(v []*GroupEntry) {
	x.xxx_hidden_Groups = &v
}

func (x *Store) SetSpaces(v []*SpaceEntry) {
	x.xxx_hidden_Spaces = &v
}

func (x *Store) SetFiles(v []*FileEntry) {
	x.xxx_hidden_Files = &v
}

func (x *Store) SetCreateTime(v int64) {
	x.xxx_hidden_CreateTime = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Store) HasCreateTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Store) ClearCreateTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_CreateTime = 0
}

type Store_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cids       []*CidEntry
	Groups     []*GroupEntry
	Spaces     []*SpaceEntry
	Files      []*FileEntry
	CreateTime *int64
}

func (b0 Store_builder) Build() *Store {
	m0 := &Store{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Cids = &b.Cids
	x.xxx_hidden_Groups = &b.Groups
	x.xxx_hidden_Spaces = &b.Spaces
	x.xxx_hidden_Files = &b.Files
	if b.CreateTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_CreateTime = *b.CreateTime
	}
	return m0
}

var File_store_proto protoreflect.FileDescriptor

const file_store_proto_rawDesc = "" +
	"\n" +
	"\vstore.proto\x12\aindexpb\"\x8c\x01\n" +
	"\bCidEntry\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04refs\x18\x04 \x01(\x05R\x04refs\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\"\xec\x01\n" +
	"\n" +
	"GroupEntry\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1a\n" +
	"\bcidCount\x18\x05 \x01(\x04R\bcidCount\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x04R\x05limit\x12\"\n" +
	"\faccountLimit\x18\a \x01(\x04R\faccountLimit\x12\x1a\n" +
	"\bspaceIds\x18\b \x03(\tR\bspaceIds\"\xca\x01\n" +
	"\n" +
	"SpaceEntry\x12\x18\n" +
	"\agroupId\x18\x01 \x01(\tR\agroupId\x12\x1e\n" +
	"\n" +
	"createTime\x18\x02 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x03 \x01(\x03R\n" +
	"updateTime\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x12\x1c\n" +
	"\tfileCount\x18\x05 \x01(\rR\tfileCount\x12\x1a\n" +
	"\bcidCount\x18\x06 \x01(\x04R\bcidCount\x12\x14\n" +
	"\x05limit\x18\a \x01(\x04R\x05limit\"s\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\tR\x04cids\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x1e\n" +
	"\n" +
	"createTime\x18\x03 \x01(\x03R\n" +
	"createTime\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x04 \x01(\x03R\n" +
	"updateTime\"\xd2\x01\n" +
	"\x05Store\x12%\n" +
	"\x04cids\x18\x01 \x03(\v2\x11.indexpb.CidEntryR\x04cids\x12+\n" +
	"\x06groups\x18\x02 \x03(\v2\x13.indexpb.GroupEntryR\x06groups\x12+\n" +
	"\x06spaces\x18\x03 \x03(\v2\x13.indexpb.SpaceEntryR\x06spaces\x12(\n" +
	"\x05files\x18\x04 \x03(\v2\x12.indexpb.FileEntryR\x05files\x12\x1e\n" +
	"\n" +
	"createTime\x18\n" +
	" \x01(\x03R\n" +
	"createTimeB\x0fZ\rindex/indexpbb\beditionsp\xe8\a"

var file_store_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_store_proto_goTypes = []any{
	(*CidEntry)(nil),   // 0: indexpb.CidEntry
	(*GroupEntry)(nil), // 1: indexpb.GroupEntry
	(*SpaceEntry)(nil), // 2: indexpb.SpaceEntry
	(*FileEntry)(nil),  // 3: indexpb.FileEntry
	(*Store)(nil),      // 4: indexpb.Store
}
var file_store_proto_depIdxs = []int32{
	0, // 0: indexpb.Store.cids:type_name -> indexpb.CidEntry
	1, // 1: indexpb.Store.groups:type_name -> indexpb.GroupEntry
	2, // 2: indexpb.Store.spaces:type_name -> indexpb.SpaceEntry
	3, // 3: indexpb.Store.files:type_name -> indexpb.FileEntry
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_store_proto_init() }
func file_store_proto_init() {
	if File_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_proto_rawDesc), len(file_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_proto_goTypes,
		DependencyIndexes: file_store_proto_depIdxs,
		MessageInfos:      file_store_proto_msgTypes,
	}.Build()
	File_store_proto = out.File
	file_store_proto_goTypes = nil
	file_store_proto_depIdxs = nil
}
