// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package lightfilenodestore

import (
	"github.com/anyproto/any-sync/app"
	"github.com/dgraph-io/badger/v4"
	blocks "github.com/ipfs/go-block-format"
	"github.com/ipfs/go-cid"
	"sync"
)

// Ensure, that configServiceMock does implement configService.
// If this is not the case, regenerate this file with moq.
var _ configService = &configServiceMock{}

// configServiceMock is a mock implementation of configService.
//
//	func TestSomethingThatUsesconfigService(t *testing.T) {
//
//		// make and configure a mocked configService
//		mockedconfigService := &configServiceMock{
//			GetFilenodeStoreDirFunc: func() string {
//				panic("mock out the GetFilenodeStoreDir method")
//			},
//			InitFunc: func(a *app.App) error {
//				panic("mock out the Init method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//		}
//
//		// use mockedconfigService in code that requires configService
//		// and then make assertions.
//
//	}
type configServiceMock struct {
	// GetFilenodeStoreDirFunc mocks the GetFilenodeStoreDir method.
	GetFilenodeStoreDirFunc func() string

	// InitFunc mocks the Init method.
	InitFunc func(a *app.App) error

	// NameFunc mocks the Name method.
	NameFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// GetFilenodeStoreDir holds details about calls to the GetFilenodeStoreDir method.
		GetFilenodeStoreDir []struct {
		}
		// Init holds details about calls to the Init method.
		Init []struct {
			// A is the a argument value.
			A *app.App
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
	}
	lockGetFilenodeStoreDir sync.RWMutex
	lockInit                sync.RWMutex
	lockName                sync.RWMutex
}

// GetFilenodeStoreDir calls GetFilenodeStoreDirFunc.
func (mock *configServiceMock) GetFilenodeStoreDir() string {
	if mock.GetFilenodeStoreDirFunc == nil {
		panic("configServiceMock.GetFilenodeStoreDirFunc: method is nil but configService.GetFilenodeStoreDir was just called")
	}
	callInfo := struct {
	}{}
	mock.lockGetFilenodeStoreDir.Lock()
	mock.calls.GetFilenodeStoreDir = append(mock.calls.GetFilenodeStoreDir, callInfo)
	mock.lockGetFilenodeStoreDir.Unlock()
	return mock.GetFilenodeStoreDirFunc()
}

// GetFilenodeStoreDirCalls gets all the calls that were made to GetFilenodeStoreDir.
// Check the length with:
//
//	len(mockedconfigService.GetFilenodeStoreDirCalls())
func (mock *configServiceMock) GetFilenodeStoreDirCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockGetFilenodeStoreDir.RLock()
	calls = mock.calls.GetFilenodeStoreDir
	mock.lockGetFilenodeStoreDir.RUnlock()
	return calls
}

// Init calls InitFunc.
func (mock *configServiceMock) Init(a *app.App) error {
	if mock.InitFunc == nil {
		panic("configServiceMock.InitFunc: method is nil but configService.Init was just called")
	}
	callInfo := struct {
		A *app.App
	}{
		A: a,
	}
	mock.lockInit.Lock()
	mock.calls.Init = append(mock.calls.Init, callInfo)
	mock.lockInit.Unlock()
	return mock.InitFunc(a)
}

// InitCalls gets all the calls that were made to Init.
// Check the length with:
//
//	len(mockedconfigService.InitCalls())
func (mock *configServiceMock) InitCalls() []struct {
	A *app.App
} {
	var calls []struct {
		A *app.App
	}
	mock.lockInit.RLock()
	calls = mock.calls.Init
	mock.lockInit.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *configServiceMock) Name() string {
	if mock.NameFunc == nil {
		panic("configServiceMock.NameFunc: method is nil but configService.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedconfigService.NameCalls())
func (mock *configServiceMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// Ensure, that StoreServiceMock does implement StoreService.
// If this is not the case, regenerate this file with moq.
var _ StoreService = &StoreServiceMock{}

// StoreServiceMock is a mock implementation of StoreService.
//
//	func TestSomethingThatUsesStoreService(t *testing.T) {
//
//		// make and configure a mocked StoreService
//		mockedStoreService := &StoreServiceMock{
//			GetBlockFunc: func(txn *badger.Txn, k cid.Cid, spaceId string, wait bool) (*BlockObj, error) {
//				panic("mock out the GetBlock method")
//			},
//			InitFunc: func(a *app.App) error {
//				panic("mock out the Init method")
//			},
//			NameFunc: func() string {
//				panic("mock out the Name method")
//			},
//			PushBlockFunc: func(txn *badger.Txn, spaceId string, block blocks.Block) error {
//				panic("mock out the PushBlock method")
//			},
//			TxUpdateFunc: func(f func(txn *badger.Txn) error) error {
//				panic("mock out the TxUpdate method")
//			},
//			TxViewFunc: func(f func(txn *badger.Txn) error) error {
//				panic("mock out the TxView method")
//			},
//		}
//
//		// use mockedStoreService in code that requires StoreService
//		// and then make assertions.
//
//	}
type StoreServiceMock struct {
	// GetBlockFunc mocks the GetBlock method.
	GetBlockFunc func(txn *badger.Txn, k cid.Cid, spaceId string, wait bool) (*BlockObj, error)

	// InitFunc mocks the Init method.
	InitFunc func(a *app.App) error

	// NameFunc mocks the Name method.
	NameFunc func() string

	// PushBlockFunc mocks the PushBlock method.
	PushBlockFunc func(txn *badger.Txn, spaceId string, block blocks.Block) error

	// TxUpdateFunc mocks the TxUpdate method.
	TxUpdateFunc func(f func(txn *badger.Txn) error) error

	// TxViewFunc mocks the TxView method.
	TxViewFunc func(f func(txn *badger.Txn) error) error

	// calls tracks calls to the methods.
	calls struct {
		// GetBlock holds details about calls to the GetBlock method.
		GetBlock []struct {
			// Txn is the txn argument value.
			Txn *badger.Txn
			// K is the k argument value.
			K cid.Cid
			// SpaceId is the spaceId argument value.
			SpaceId string
			// Wait is the wait argument value.
			Wait bool
		}
		// Init holds details about calls to the Init method.
		Init []struct {
			// A is the a argument value.
			A *app.App
		}
		// Name holds details about calls to the Name method.
		Name []struct {
		}
		// PushBlock holds details about calls to the PushBlock method.
		PushBlock []struct {
			// Txn is the txn argument value.
			Txn *badger.Txn
			// SpaceId is the spaceId argument value.
			SpaceId string
			// Block is the block argument value.
			Block blocks.Block
		}
		// TxUpdate holds details about calls to the TxUpdate method.
		TxUpdate []struct {
			// F is the f argument value.
			F func(txn *badger.Txn) error
		}
		// TxView holds details about calls to the TxView method.
		TxView []struct {
			// F is the f argument value.
			F func(txn *badger.Txn) error
		}
	}
	lockGetBlock  sync.RWMutex
	lockInit      sync.RWMutex
	lockName      sync.RWMutex
	lockPushBlock sync.RWMutex
	lockTxUpdate  sync.RWMutex
	lockTxView    sync.RWMutex
}

// GetBlock calls GetBlockFunc.
func (mock *StoreServiceMock) GetBlock(txn *badger.Txn, k cid.Cid, spaceId string, wait bool) (*BlockObj, error) {
	if mock.GetBlockFunc == nil {
		panic("StoreServiceMock.GetBlockFunc: method is nil but StoreService.GetBlock was just called")
	}
	callInfo := struct {
		Txn     *badger.Txn
		K       cid.Cid
		SpaceId string
		Wait    bool
	}{
		Txn:     txn,
		K:       k,
		SpaceId: spaceId,
		Wait:    wait,
	}
	mock.lockGetBlock.Lock()
	mock.calls.GetBlock = append(mock.calls.GetBlock, callInfo)
	mock.lockGetBlock.Unlock()
	return mock.GetBlockFunc(txn, k, spaceId, wait)
}

// GetBlockCalls gets all the calls that were made to GetBlock.
// Check the length with:
//
//	len(mockedStoreService.GetBlockCalls())
func (mock *StoreServiceMock) GetBlockCalls() []struct {
	Txn     *badger.Txn
	K       cid.Cid
	SpaceId string
	Wait    bool
} {
	var calls []struct {
		Txn     *badger.Txn
		K       cid.Cid
		SpaceId string
		Wait    bool
	}
	mock.lockGetBlock.RLock()
	calls = mock.calls.GetBlock
	mock.lockGetBlock.RUnlock()
	return calls
}

// Init calls InitFunc.
func (mock *StoreServiceMock) Init(a *app.App) error {
	if mock.InitFunc == nil {
		panic("StoreServiceMock.InitFunc: method is nil but StoreService.Init was just called")
	}
	callInfo := struct {
		A *app.App
	}{
		A: a,
	}
	mock.lockInit.Lock()
	mock.calls.Init = append(mock.calls.Init, callInfo)
	mock.lockInit.Unlock()
	return mock.InitFunc(a)
}

// InitCalls gets all the calls that were made to Init.
// Check the length with:
//
//	len(mockedStoreService.InitCalls())
func (mock *StoreServiceMock) InitCalls() []struct {
	A *app.App
} {
	var calls []struct {
		A *app.App
	}
	mock.lockInit.RLock()
	calls = mock.calls.Init
	mock.lockInit.RUnlock()
	return calls
}

// Name calls NameFunc.
func (mock *StoreServiceMock) Name() string {
	if mock.NameFunc == nil {
		panic("StoreServiceMock.NameFunc: method is nil but StoreService.Name was just called")
	}
	callInfo := struct {
	}{}
	mock.lockName.Lock()
	mock.calls.Name = append(mock.calls.Name, callInfo)
	mock.lockName.Unlock()
	return mock.NameFunc()
}

// NameCalls gets all the calls that were made to Name.
// Check the length with:
//
//	len(mockedStoreService.NameCalls())
func (mock *StoreServiceMock) NameCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockName.RLock()
	calls = mock.calls.Name
	mock.lockName.RUnlock()
	return calls
}

// PushBlock calls PushBlockFunc.
func (mock *StoreServiceMock) PushBlock(txn *badger.Txn, spaceId string, block blocks.Block) error {
	if mock.PushBlockFunc == nil {
		panic("StoreServiceMock.PushBlockFunc: method is nil but StoreService.PushBlock was just called")
	}
	callInfo := struct {
		Txn     *badger.Txn
		SpaceId string
		Block   blocks.Block
	}{
		Txn:     txn,
		SpaceId: spaceId,
		Block:   block,
	}
	mock.lockPushBlock.Lock()
	mock.calls.PushBlock = append(mock.calls.PushBlock, callInfo)
	mock.lockPushBlock.Unlock()
	return mock.PushBlockFunc(txn, spaceId, block)
}

// PushBlockCalls gets all the calls that were made to PushBlock.
// Check the length with:
//
//	len(mockedStoreService.PushBlockCalls())
func (mock *StoreServiceMock) PushBlockCalls() []struct {
	Txn     *badger.Txn
	SpaceId string
	Block   blocks.Block
} {
	var calls []struct {
		Txn     *badger.Txn
		SpaceId string
		Block   blocks.Block
	}
	mock.lockPushBlock.RLock()
	calls = mock.calls.PushBlock
	mock.lockPushBlock.RUnlock()
	return calls
}

// TxUpdate calls TxUpdateFunc.
func (mock *StoreServiceMock) TxUpdate(f func(txn *badger.Txn) error) error {
	if mock.TxUpdateFunc == nil {
		panic("StoreServiceMock.TxUpdateFunc: method is nil but StoreService.TxUpdate was just called")
	}
	callInfo := struct {
		F func(txn *badger.Txn) error
	}{
		F: f,
	}
	mock.lockTxUpdate.Lock()
	mock.calls.TxUpdate = append(mock.calls.TxUpdate, callInfo)
	mock.lockTxUpdate.Unlock()
	return mock.TxUpdateFunc(f)
}

// TxUpdateCalls gets all the calls that were made to TxUpdate.
// Check the length with:
//
//	len(mockedStoreService.TxUpdateCalls())
func (mock *StoreServiceMock) TxUpdateCalls() []struct {
	F func(txn *badger.Txn) error
} {
	var calls []struct {
		F func(txn *badger.Txn) error
	}
	mock.lockTxUpdate.RLock()
	calls = mock.calls.TxUpdate
	mock.lockTxUpdate.RUnlock()
	return calls
}

// TxView calls TxViewFunc.
func (mock *StoreServiceMock) TxView(f func(txn *badger.Txn) error) error {
	if mock.TxViewFunc == nil {
		panic("StoreServiceMock.TxViewFunc: method is nil but StoreService.TxView was just called")
	}
	callInfo := struct {
		F func(txn *badger.Txn) error
	}{
		F: f,
	}
	mock.lockTxView.Lock()
	mock.calls.TxView = append(mock.calls.TxView, callInfo)
	mock.lockTxView.Unlock()
	return mock.TxViewFunc(f)
}

// TxViewCalls gets all the calls that were made to TxView.
// Check the length with:
//
//	len(mockedStoreService.TxViewCalls())
func (mock *StoreServiceMock) TxViewCalls() []struct {
	F func(txn *badger.Txn) error
} {
	var calls []struct {
		F func(txn *badger.Txn) error
	}
	mock.lockTxView.RLock()
	calls = mock.calls.TxView
	mock.lockTxView.RUnlock()
	return calls
}
