name: nix

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check flake
        run: nix flake check --all-systems

      - name: Build package
        run: nix build -L .#default

      - name: Run binary version check
        run: nix run .#any-sync-bundle -- --version

  devShell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8

      - name: Check dev shell
        run: |
          nix develop --command go version
          nix develop --command golangci-lint version
          nix develop --command goreleaser --version
