name: release

on:
  push:
    tags:
      - "v*"

permissions:
  packages: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0 # Required for goreleaser to get git history

      - uses: actions/setup-go@v6
        with:
          go-version: "1.25.1"

      - name: Set up QEMU for cross-compilation of Docker images
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Fix Segmentation fault or QEMU - https://github.com/docker/buildx/issues/1170
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

      - uses: goreleaser/goreleaser-action@v6
        id: goreleaser
        with:
          distribution: goreleaser
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker base on Goreleaser
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ fromJSON(steps.goreleaser.outputs.metadata).version }}

      - name: Build and push Docker image (stage-release-minimal)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          target: stage-release-minimal
          tags: |
            ghcr.io/${{ github.repository }}:minimal
            ${{ steps.meta.outputs.tags }}-minimal
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ fromJSON(steps.goreleaser.outputs.metadata).version }}
            COMMIT=${{ fromJSON(steps.goreleaser.outputs.metadata).commit }}
            COMMIT_DATE=${{ fromJSON(steps.goreleaser.outputs.metadata).date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true

      - name: Build and push Docker image (stage-release)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          platforms: |
            linux/arm64
            linux/amd64
          target: stage-release
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ fromJSON(steps.goreleaser.outputs.metadata).version }}
            COMMIT=${{ fromJSON(steps.goreleaser.outputs.metadata).commit }}
            COMMIT_DATE=${{ fromJSON(steps.goreleaser.outputs.metadata).date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: true
          sbom: true
